apiVersion: v1
kind: Pod
metadata:
  name: interactive-pod
  namespace: test
spec:
  containers:
    - name: benchmark-runner
      image: "docker.io/rgshaw2/interactive-pod:0.2"
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          cpu: "8"
          memory: "4Gi"
        limits:
          cpu: "8"
          memory: "4Gi"
