apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-model
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vllm-model
  template:
    metadata:
      labels:
        name: vllm-model
    spec:
      containers:
        - name: vllm-model
          image: "docker.io/vllm/vllm-openai:v0.9.2"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve unsloth/Llama-3.3-70B-Instruct --tensor-parallel-size 4 --max-model-len 32000 --disable-log-requests"
          ]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
            requests:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
          env:
            - name: VLLM_TORCH_PROFILER_DIR
              value: "/code/traces"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-model
  namespace: test
spec:
  type: ClusterIP
  selector:
    name: vllm-model
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
