apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-tp1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vllm-tp1
  template:
    metadata:
      labels:
        name: vllm-tp1
    spec:
      containers:
        - name: vllm-tp1
          image: "docker.io/vllm/vllm-openai:v0.9.2"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic --tensor-parallel-size 1 --max-model-len 32000 --disable-log-requests"
          ]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 1
            requests:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-tp1
  namespace: test
spec:
  type: ClusterIP
  selector:
    name: vllm-tp1
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
