apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-midstream
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vllm-midstream
  template:
    metadata:
      labels:
        name: vllm-midstream
    spec:
      containers:
        - name: vllm-midstream
          image: "quay.io/vllm/vllm-cuda:0.9.2.2"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic --tensor-parallel-size 4 --max-model-len 32000 --disable-log-requests"
          ]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
            requests:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          env:
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: HF_HUB_DISABLE_XET
              value: "1"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "0"
            - name: TRITON_LIBCUDA_PATH
              value: "/usr/lib64"
      imagePullSecrets:
        - name: redhat-registry-secret
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-midstream
  namespace: test
spec:
  type: ClusterIP
  selector:
    name: vllm-midstream
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
